spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq_bot?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: admin

qq:
  id: 123456
  password: 123456

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error