spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq_bot?serverTimezone=Asia/Shanghai
    hikari:
      username: 123
      password: 123
  application:
    name: process
  rabbitmq:
    addresses: 123
    port: 123
    virtual-host: dev
    username: 123
    password: 123
    listener:
      simple:
        prefetch: 1
        retry:
          initial-interval: 5000
          max-attempts: 10
          enabled: true
      default-requeue-rejected: true


logging:
  config: classpath:log4j2.xml

macAddress: 123

baseFilePath: /root/qq_bot/img

templateFilePath: /root/qq_bot/template

tmpFilePath: /root/qq_bot/tmpfile


sgdz_account: 123

sgdz_password: 123